--[SQL] 250122 실습 11번

--쇼핑 카테고리 데이터의 순방향 계층 구조에서 동일한 부모를 가진 카테고리들에 대해 이름순으로 정렬하시오.
SELECT CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY_ID,
  SUBSTR(SYS_CONNECT_BY_PATH(CATEGORY_NAME, ' -> '), 5) PATH
FROM SHOPPING_CATEGORIES
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID
ORDER SIBLINGS BY CATEGORY_NAME;

--이름에 'Phones'가 포함된 카테고리와 해당 계층 구조를 순방향으로 출력하시오.
SELECT CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY_ID,
  SUBSTR(SYS_CONNECT_BY_PATH(CATEGORY_NAME, ' -> '), 5) PATH
FROM SHOPPING_CATEGORIES
START WITH CATEGORY_NAME LIKE '%Phones%'
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;

--쇼핑 카테고리 데이터의 순방향 계층 구조에서 depth가 가장 깊은 LEVEL 값을 구하시오.
SELECT MAX(LEVEL) MAX_DEPTH
FROM SHOPPING_CATEGORIES
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;

--depth가 가장 깊은 LEVEL 값을 가지는 데이터를 출력하시오.
SELECT CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY_ID, LEVEL,
  SUBSTR(SYS_CONNECT_BY_PATH(CATEGORY_NAME, ' -> '), 5) PATH
FROM SHOPPING_CATEGORIES
WHERE LEVEL = (
    SELECT MAX(LEVEL)
    FROM SHOPPING_CATEGORIES
    START WITH PARENT_CATEGORY_ID IS NULL
    CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID
)
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;