--[SQL] 250122 연습문제

--1. 직원 계층에서 상사의 이름 표시
--직원의 계층 구조를 조회하되 각 계층에서 상사 이름도 함께 표시하세요.
--출력 컬럼은 LEVEL, 사번, 이름, 직무, 상사의 사번, 상사의 이름입니다.
--(단, 상사가 없는 경우 ‘대표’라고 표시하고 계층별로 이름으로 오름차순 정렬합니다.)
SELECT LEVEL, EMPLOYEE_ID, NAME EMPLOYEE_NAME, JOB_ID, MANAGER_ID,
  NVL((SELECT NAME FROM EMPLOYEES WHERE E.MANAGER_ID = EMPLOYEE_ID), '대표') MANAGER_NAME
FROM EMPLOYEES E
START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
ORDER SIBLINGS BY EMPLOYEE_NAME;

--2. 각 계층별 급여 순위
--직원 계층 쿼리를 작성하고 각 계층별로 급여 상위 3위 까지의 직원들만 조회하세요.
--출력 컬럼은 LEVEL, 사번, 이름, 급여입니다.
SELECT "LEVEL", EMPLOYEE_ID, NAME, SALARY
FROM (
  SELECT LEVEL, EMPLOYEE_ID, NAME, SALARY,
    RANK() OVER (PARTITION BY LEVEL ORDER BY SALARY DESC) rank
  FROM EMPLOYEES
  WHERE SALARY IS NOT NULL
  START WITH MANAGER_ID IS NULL
  CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
)
WHERE rank <= 3;

--3. 각 계층별 평균 급여
--직원 계층 구조를 생성하고 각 계층별 평균 급여와 함께 출력하세요.
--출력 컬럼은 LEVEL, 사번, 이름, 급여, 해당 계층의 평균 급여이고 평균 급여는 반올림하여 정수로 표현합니다.
SELECT E1."LEVEL", E1.EMPLOYEE_ID, E1.NAME, E1.SALARY, E2.AVG_SALARY
FROM (
  SELECT LEVEL, EMPLOYEE_ID, NAME, SALARY
  FROM EMPLOYEES
  START WITH MANAGER_ID IS NULL
  CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
) E1,(
  SELECT EMPLOYEE_ID,
    ROUND(AVG(SALARY) OVER (PARTITION BY LEVEL)) AVG_SALARY
  FROM EMPLOYEES
  START WITH MANAGER_ID IS NULL
  CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
) E2
WHERE E1.EMPLOYEE_ID = E2.EMPLOYEE_ID;

--계층 구조가 무너진다.
SELECT LEVEL, EMPLOYEE_ID, NAME, SALARY,
  ROUND(AVG(SALARY) OVER (PARTITION BY LEVEL)) AVG_SALARY
FROM EMPLOYEES
START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

--4. 상사와의 급여 비교
--직원의 급여가 상사의 급여보다 높은 경우만 조회하세요.
--출력 컬럼은 사번, 이름, 급여, 상사 이름, 상사의 급여입니다.
SELECT E1.EMPLOYEE_ID, E1.NAME EMPLOYEE_NAME, E1.SALARY EMPLOYEE_SALARY,
  E2.NAME MANAGER_NAME, E2.SALARY MANAGER_SALARY
FROM EMPLOYEES E1, EMPLOYEES E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID
  AND E1.SALARY > E2.SALARY;

--5. 직원의 부서 경로 조회
--각 직원이 속한 부서를 포함하여 해당 직원의 부서명 경로를 표시하세요.
--부서가 없는 경우 "No DEPT"로 표시하세요. 출력 컬럼은 이름, 부서명, 부서명 경로입니다.
SELECT E.NAME, 
  NVL((SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = E.DEPARTMENT_ID), 'No DEPT') DEPARTMENT_NAME,
  SUBSTR(SYS_CONNECT_BY_PATH(
    NVL((SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = E.DEPARTMENT_ID), 'No DEPT')
    , ' -> '), 5
  ) PATH
FROM EMPLOYEES E
START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

SELECT E.NAME,
  NVL(D.DEPARTMENT_NAME, 'No DEPT') DEPARTMENT_NAME,
  SUBSTR(SYS_CONNECT_BY_PATH(NVL(D.DEPARTMENT_NAME, 'No DEPT'), ' -> '), 5) PATH
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
START WITH E.MANAGER_ID IS NULL
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID;

--6. 직무별, 지역별 대출 금액 합계 조회
--대출 테이블에서 직무별, 지점별 대출 금액 합계를 계산하고 모든 조합, 즉 다차원 집계를 표시하세요.
SELECT E.JOB_ID, L.BRANCH_ID, SUM(AMOUNT) TOTAL_AMOUNT
FROM EMPLOYEES E, LOANS L
WHERE E.EMPLOYEE_ID = L.CUSTOMER_ID
GROUP BY CUBE(E.JOB_ID, L.BRANCH_ID)
ORDER BY E.JOB_ID, L.BRANCH_ID;

--7. 직원 급여 통계 요약 (GROUPING SETS)
--사원 테이블에서 전체 급여 합계, 부서별 급여 합계, 직무별 급여 합계를 각각 표시하세요.
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) TOTAL_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_ID, JOB_ID, ())
ORDER BY DEPARTMENT_ID, JOB_ID;

--8. 대출 통계 요약
--대출 테이블에서 지점별, 대출 상태별 금액 합계를 계산하고 각 지점별 소계와 전체 합계를 표시하세요.
--단, 지점별 소계를 나타내는 행은 상태값 컬럼에 ‘==========’ 표시를 해주고 총계는 ‘Total’로 표시합니다.
SELECT NVL(TO_CHAR(BRANCH_ID), 'Total') BRANCH_ID,
  NVL(STATUS, '==========') STATUS,
  SUM(AMOUNT) TOTAL_AMOUNT
FROM LOANS L
GROUP BY ROLLUP(BRANCH_ID, STATUS)
ORDER BY L.BRANCH_ID;

--9. 계층별 직원 수 조회
--직원의 계층 구조를 생성하고 각 계층별 직원의 수를 출력하세요.
SELECT LEVEL, COUNT(*) COUNT
FROM EMPLOYEES
START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
GROUP BY LEVEL;

--10. 고객별, 대출 상태별 대출 금액
--고객별, 대출 상태별 대출 금액과 고객별 대출 금액 소계, 그리고 전체 대출 금액 합계를 구하세요.
--출력 컬럼은 고객 이름, 대출 상태, 대출 금액입니다.
--고객별 대출 금액 소계는 ‘All Status’로 표시하고 전체 대출 금액 합계는 Total로 표시해 주세요.
SELECT NVL((SELECT NAME FROM CUSTOMERS WHERE CUSTOMER_ID = L.CUSTOMER_ID), 'Total') NAME,
  NVL(L.STATUS, 'All Status') STAUTS,
  SUM(L.AMOUNT) TOTAL_AMOUNT
FROM LOANS L
GROUP BY ROLLUP(L.CUSTOMER_ID, L.STATUS)
ORDER BY L.CUSTOMER_ID, L.STATUS; 
