--[SQL] 250115 실습 6번

--승인된 대출(APPROVED)의 총 대출 금액과 해당 대출 건수를 출력하시오.
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT, COUNT(LOAN_ID) AS LOAN_COUNT
FROM LOANS
WHERE STATUS = 'APPROVED';

--각 월별 총 거래 금액을 계산하고, 거래 금액이 10,000 이상인 달만 출력하시오.
SELECT TO_CHAR(TRANSACTION_DATE, 'MONTH') AS MONTH, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANSACTION_DATE, 'MONTH')
HAVING SUM(AMOUNT) >= 10000;

--각 지점에서 승인된 대출(APPROVED)의 평균 대출 금액과 총 대출 금액을 계산하시오.
SELECT BRANCH_ID, AVG(AMOUNT) AS AVG_AMOUNT, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID;
