--[SQL] 250121 실습 10번

--거래 테이블에서 계좌별 누적 거래 금액을 계산하시오.
SELECT ACCOUNT_ID, TRANSACTION_DATE,
  SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID
    ORDER BY TRANSACTION_DATE) CUM_AMOUNT
FROM TRANSACTIONS;

--각 계좌별 거래 금액의 최고 거래 금액 대비 비율을 출력하시오. (AMOUNT / MAX AMOUNT)
SELECT ACCOUNT_ID, TRANSACTION_ID,
  ROUND(AMOUNT / MAX(AMOUNT) OVER (PARTITION BY ACCOUNT_ID), 2) AMOUNT_RATIO
FROM TRANSACTIONS;

--대출 테이블에서 지점별 누적 대출 금액을 계산하시오.
SELECT BRANCH_ID, LOAN_DATE,
  SUM(AMOUNT) OVER (PARTITION BY BRANCH_ID
    ORDER BY LOAN_DATE
    ROWS UNBOUNDED PRECEDING) CUM_AMOUNT
FROM LOANS;

--계좌 테이블에서 고객별 평균 잔액을 계산하시오.
--(반올림하여 소수점 둘째 자리까지 출력)
SELECT DISTINCT CUSTOMER_ID,
  ROUND(AVG(BALANCE) OVER (PARTITION BY CUSTOMER_ID), 2) AVG_BALANCE
FROM ACCOUNTS
ORDER BY CUSTOMER_ID;