--[SQL] 250121 연습문제

--1. 직무별 상위 3명의 직원
--각 직무별로 급여가 가장 높은 3명의 직원 정보를 조회하세요. 출력 컬럼은 직무, 사번, 이름, 급여, 순위이고 직무, 순위로 정렬합니다.
SELECT *
FROM (
  SELECT JOB_ID, EMPLOYEE_ID, NAME, SALARY,
    RANK() OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) rank
    FROM EMPLOYEES
    WHERE SALARY IS NOT NULL
)
WHERE rank <= 3;

--2. 직원 입사 연도별 총 급여 및 누적 급여
--직원들의 입사 연도별 총 급여와 해당 연도의 누적 급여를 계산하세요.
SELECT YEAR, TOTAL_SALARY,
  SUM(TOTAL_SALARY) OVER (ORDER BY YEAR) CUM_SALARY
FROM (
  SELECT DISTINCT TO_CHAR(HIRE_DATE, 'YYYY') YEAR,
    SUM(SALARY) OVER (PARTITION BY TO_CHAR(HIRE_DATE, 'YYYY')) TOTAL_SALARY
  FROM EMPLOYEES
);

SELECT YEAR, TOTAL_SALARY,
  SUM(TOTAL_SALARY) OVER (ORDER BY YEAR) CUM_SALARY
FROM (
  SELECT TO_CHAR(HIRE_DATE, 'YYYY') YEAR, SUM(SALARY) TOTAL_SALARY
  FROM EMPLOYEES
  GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
);

--3. 직원별 급여 순위와 부서 평균 급여 비교
--모든 직원에 대해 급여 순위를 계산하고, 각 직원의 급여가 부서 평균 급여보다 높은지 확인하세요.
--부서 평균 급여보다 높은 경우 ‘높다’라고 출력하고 낮은 경우 ‘낮다’라고 출력합니다.
--(출력 컬럼은 사번, 이름, 급여, 급여 순위, 부서 평균 급여, 높은지 낮은지 여부)
SELECT EMPLOYEE_ID, NAME, SALARY,
  RANK() OVER (ORDER BY SALARY DESC) rank,
  ROUND(AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID), 2) AVG_SALARY,
  CASE
    WHEN SALARY >= AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) THEN '높다'
    ELSE '낮다'
  END SALARY_LEVEL
FROM EMPLOYEES
WHERE SALARY IS NOT NULL;

--4. 최근 1년간 대출을 받은 고객 중 총 대출 금액 상위 5명
--최근 1년 동안 대출을 받은 고객의 총 대출 금액을 계산하고, 이 금액이 상위 5명인 고객의 이름과 대출 금액을 출력하세요.
SELECT *
FROM (
  SELECT DISTINCT
    (SELECT NAME FROM CUSTOMERS WHERE CUSTOMER_ID = L.CUSTOMER_ID) NAME,
    SUM(L.AMOUNT) OVER (PARTITION BY L.CUSTOMER_ID) TOTAL_AMOUNT
  FROM LOANS L
  WHERE L.LOAN_DATE >= ADD_MONTHS(SYSDATE, -12)
  ORDER BY TOTAL_AMOUNT DESC
)
WHERE ROWNUM <= 5;

--5. 이동 평균 (Moving Average)
--직원 테이블에서 직원의 급여(SALARY)를 기준으로 직원 ID 순서대로 3명의 이동 평균을 계산하세요.
--여기서 이동 평균은 현재 직원의 급여와 바로 이전 직원 2명의 급여를 포함합니다. 직원 ID, 이름, 급여, 그리고 이동 평균을 출력하세요.
--이동 평균값은 반올림하여 소수점 아래 둘째 자리까지 표현합니다.
SELECT EMPLOYEE_ID, NAME, SALARY,
  ROUND(AVG(SALARY) OVER (ORDER BY EMPLOYEE_ID ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) MOV_AVG
FROM EMPLOYEES;

--6. 계좌 잔액이 평균 잔액 이상인 고객과 대출 금액이 평균 대출 금액 이상인 고객의 병합
--계좌 잔액이 전 계좌의 평균 잔액 이상인 고객과 대출 금액이 전체 평균 대출 금액 이상인 고객을 병합하여 고객 이름과 금액을 조회하세요.
--출력 데이터에 출처가 "계좌"인지 "대출"인지도 하나의 컬럼으로 나타내 주세요.
SELECT C.NAME, A.BALANCE, '계좌' SOURCE
FROM CUSTOMERS C
LEFT OUTER JOIN ACCOUNTS A
  ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE A.BALANCE >= (SELECT AVG(BALANCE) FROM ACCOUNTS)
UNION
SELECT C.NAME, L.AMOUNT, '대출' SOURCE
FROM CUSTOMERS C
LEFT OUTER JOIN LOANS L
  ON C.CUSTOMER_ID = L.CUSTOMER_ID
WHERE L.AMOUNT >= (SELECT AVG(AMOUNT) FROM LOANS);

--7. 직무별 평균 급여가 부서별 평균 급여 이상인 직무 조회
--직무별 평균 급여가 소속된 부서의 평균 급여 이상인 경우를 조회하세요.
--출력 데이터는 직무 ID, 부서 이름, 직무별 평균 급여, 부서별 평균 급여입니다.
--각 평균 급여는 반올림하여 정수로 표현해 주세요.
SELECT *
FROM (
  SELECT DISTINCT E.JOB_ID,
    (SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) DEPARTMENT_NAME,
    ROUND(AVG(E.SALARY) OVER (PARTITION BY E.JOB_ID)) AVG_SALARY_JOB,
    ROUND(AVG(E.SALARY) OVER (PARTITION BY E.DEPARTMENT_ID)) AVG_SALARY_DEPT
  FROM EMPLOYEES E
  WHERE DEPARTMENT_ID IS NOT NULL
)
WHERE AVG_SALARY_JOB >= AVG_SALARY_DEPT;
  
--8. 지점별 고객 수와 승인율
--지점별 대출 건수를 계산하고, 대출 승인율(APPROVED 상태 건수 / 전체 건수 * 100)을 계산하여 결과를 출력하세요.
--대출 승인율은 반올림하여 소수점 아래 둘째 자리까지 표현합니다.
SELECT BRANCH_ID,
  COUNT(LOAN_ID) TOTAL_LOAN,
  ROUND(COUNT(CASE WHEN STATUS = 'APPROVED' THEN LOAN_ID END) / COUNT(LOAN_ID) * 100, 2) APPROVED_RATIO
FROM LOANS
GROUP BY BRANCH_ID;

SELECT BRANCH_ID, TOTAL_LOAN, ROUND(APPROVED_LOAN / TOTAL_LOAN * 100, 2) APPROVED_RATIO
FROM (
  SELECT DISTINCT BRANCH_ID,
    COUNT(LOAN_ID) OVER (PARTITION BY BRANCH_ID) TOTAL_LOAN,
    COUNT(CASE WHEN STATUS = 'APPROVED' THEN LOAN_ID END) OVER (PARTITION BY BRANCH_ID) AS APPROVED_LOAN
  FROM LOANS
);

--9. 직무별 최고 급여를 받는 직원
--각 직무에서 가장 높은 급여를 받는 직원의 이름과 급여를 조회하세요.
--직무 기준으로 정렬하세요.
SELECT JOB_ID, NAME, SALARY
FROM (
  SELECT JOB_ID, NAME, SALARY,
    MAX(SALARY) OVER (PARTITION BY JOB_ID) MAX_SALARY
  FROM EMPLOYEES
)
WHERE SALARY = MAX_SALARY
ORDER BY JOB_ID;

SELECT E.JOB_ID, E.NAME, E.SALARY
FROM EMPLOYEES E
WHERE (E.JOB_ID, E.SALARY) IN (
  SELECT JOB_ID, MAX(SALARY)
  FROM EMPLOYEES
  GROUP BY JOB_ID
)
ORDER BY E.JOB_ID;

--10. 상사와 직원 관계를 기반으로 부서별 직원 통계
--각 부서에서 상사가 있는 직원의 수와 상사가 없는 직원의 수를 계산하세요.
--부서 이름과 각 통계 값을 출력하세요.
SELECT (
  SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
  WHERE DEPARTMENT_ID = E.DEPARTMENT_ID
) DEPARTMENT_NAME,
  COUNT(CASE WHEN E.MANAGER_ID IS NOT NULL THEN E.EMPLOYEE_ID END) IS_MANAGER,
  COUNT(CASE WHEN E.MANAGER_ID IS NULL THEN E.EMPLOYEE_ID END) IS_NOT_MANAGER
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IS NOT NULL
GROUP BY E.DEPARTMENT_ID;

SELECT (
  SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS
  WHERE DEPARTMENT_ID = E.DEPARTMENT_ID
) DEPARTMENT_NAME,
  COUNT(MANAGER_ID) IS_MANAGER,
  COUNT(*) - COUNT(MANAGER_ID) IS_NOT_MANAGER
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IS NOT NULL
GROUP BY E.DEPARTMENT_ID;