--[SQL] 250120 실습 8번

--지점 이름이 'Location 1'에 해당하는 지점에서 대출을 받은 고객의 이름을 출력하시오.
SELECT NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
  SELECT CUSTOMER_ID
  FROM LOANS
  WHERE BRANCH_ID IN (
    SELECT BRANCH_ID
    FROM BRANCHES
    WHERE LOCATION = 'Location 1'
  )
);

SELECT NAME
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (
  SELECT L.CUSTOMER_ID
  FROM LOANS L, BRANCHES B
  WHERE L.BRANCH_ID = B.BRANCH_ID
    AND B.LOCATION = 'Location 1'
);

--특정 고객(CUSTOMER_ID=100)이 소유한 모든 계좌에서 발생한 거래를 출력하시오.
SELECT TRANSACTION_ID
FROM TRANSACTIONS
WHERE ACCOUNT_ID IN (
  SELECT ACCOUNT_ID
  FROM ACCOUNTS 
  WHERE CUSTOMER_ID = 100
);

--각 고객이 보유한 계좌 중 가장 높은 잔액을 가진 계좌를 조회하시오.
SELECT CUSTOMER_ID, ACCOUNT_ID, BALANCE
FROM ACCOUNTS A1
WHERE BALANCE = (
  SELECT MAX(BALANCE)
  FROM ACCOUNTS A2
  WHERE A1.CUSTOMER_ID = A2.CUSTOMER_ID
);