--[SQL] 250116 연습문제

--1. 직원과 부서 정보 조회
--직원 이름과 소속 부서의 근무지를 조회하세요.
SELECT E.NAME, D.LOCATION
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--2. 직원과 매니저 정보 조회
--직원 이름과 해당 직원의 매니저 이름을 조회하세요. (단, 매니저가 없는 직원도 출력)
SELECT E1.NAME AS EMPLOYEE, E2.NAME AS MANAGER
FROM EMPLOYEES E1
LEFT OUTER JOIN EMPLOYEES E2
  ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

--3. 직원과 급여 정보 조회
--직원 이름과 급여를 조회하되 급여가 NULL인 경우 N/A로 출력하세요.  
SELECT NAME, NVL(TO_CHAR(SALARY), 'N/A') AS SALARY
FROM EMPLOYEES;

SELECT NAME, NVL2(SALARY, TO_CHAR(SALARY), 'N/A') AS SALARY
FROM EMPLOYEES;

--4. 특정 부서 직원 조회
--근무지가 Chicago인 직원 이름과 급여를 조회하세요.
SELECT E.NAME, E.SALARY
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND D.LOCATION = 'Chicago';

--5. 특정 급여 범위 조회
--급여가 5000 이상 10000 이하인 직원의 이름과 급여, 부서명을 조회하세요.
SELECT E.NAME, E.SALARY, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.SALARY BETWEEN 5000 AND 10000;
    
--6. 최근 3개월 내 입사한 직원
--최근 3개월 이내 입사한 직원 이름과 입사일을 조회하시오.
SELECT NAME, HIRE_DATE
FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) <= 3;

SELECT NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE >= SYSDATE - (INTERVAL '3' MONTH);

--7. 부서장 이름 조회
--각 부서의 부서장 이름과 부서 이름을 조회하세요.
SELECT D.DEPARTMENT_NAME, E.NAME
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
  ON D.MANAGER_ID = E.EMPLOYEE_ID;

--8. 직무별 직원 수 조회
--직무별 직원 수를 출력하세요.
SELECT JOB_ID, COUNT(*) COUNT_JOB_ID
FROM EMPLOYEES
GROUP BY JOB_ID;

--9. 부서별 평균 급여
--부서명과 부서별 평균 급여를 조회하세요. (단, 평균 급여는 올림하여 출력)
SELECT D.DEPARTMENT_NAME, NVL(CEIL(AVG(E.SALARY)), 0) AS AVG_SALARY
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;

--10. 직원의 총 급여 합계
--직원의 총 급여 합계를 조회하세요.
SELECT SUM(SALARY) TOTAL_SALARY
FROM EMPLOYEES;

--11. 대출 정보와 고객 이름 조회
--대출 금액과 고객 이름을 대출 금액이 높은 사람부터 조회하세요.
SELECT C.NAME, L.AMOUNT
FROM CUSTOMERS C
LEFT OUTER JOIN LOANS L
  ON C.CUSTOMER_ID = L.CUSTOMER_ID
ORDER BY L.AMOUNT DESC NULLS LAST;

--12. 대출 상태별 고객 수
--대출 상태별 고객 수를 조회하세요.
SELECT STATUS, COUNT(DISTINCT CUSTOMER_ID) COUNT
FROM LOANS
GROUP BY STATUS;

--13. 직원 수가 가장 적은 부서
--직원 수가 가장 적은 부서의 부서 ID와 직원 수를 조회하세요.
SELECT DEPARTMENT_ID, COUNT(*) COUNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) = (SELECT MIN(COUNT(*))  --서브 쿼리
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID IS NOT NULL
  GROUP BY DEPARTMENT_ID
);

SELECT *
FROM (
  SELECT DEPARTMENT_ID, COUNT(*)
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID IS NOT NULL
  GROUP BY DEPARTMENT_ID
  ORDER BY COUNT(*)
)
WHERE ROWNUM = 1;

--14. 월별 신규 고객 수
--월별 신규 고객 수를 최근순으로 조회하세요.
SELECT TO_CHAR(CREATED_AT, 'YYYY-MM') MONTH, COUNT(*) COUNT
FROM CUSTOMERS
GROUP BY TO_CHAR(CREATED_AT, 'YYYY-MM')
ORDER BY MONTH DESC;

--15. 상품 카테고리 계층 구조 조회
--상품 카테고리와 상위 카테고리를 조회하세요. (단, 상위 카테고리가 없는 데이터도 출력)
SELECT S1.CATEGORY_NAME CHILD, S2.CATEGORY_NAME PARENT
FROM SHOPPING_CATEGORIES S1
LEFT OUTER JOIN SHOPPING_CATEGORIES S2
  ON S1.PARENT_CATEGORY_ID = S2.CATEGORY_ID;

--16. 특정 지점의 대출 합계
--Branch 8 지점의 대출 총합을 조회하세요. (단, 소수점 아래는 버림)
SELECT B.NAME, FLOOR(SUM(L.AMOUNT)) TOTAL_AMOUNT
FROM BRANCHES B, LOANS L
WHERE B.BRANCH_ID = L.BRANCH_ID AND B.NAME = 'Branch 8'
GROUP BY B.NAME;

--17. 직무별 직원의 평균 급여와 급여 등급 조회
--직무별 직원의 평균 급여를 계산하여 평균 급여가 5000 이상인 경우만 출력합니다. 평균 급여가 8000 이상인 경우 "HIGH", 6000 이상 8000 미만인 경우 "MEDIUM", 6000 미만인 경우 "LOW"로 표시합니다. 결과는 평균 급여가 높은 순으로 정렬하세요.
SELECT JOB_ID, ROUND(AVG(SALARY), 2) AVG_SALARY,
  CASE
    WHEN AVG(SALARY) >= 8000 THEN 'HIGH'
    WHEN AVG(SALARY) >= 6000 THEN 'MEDIUM'
    ELSE 'LOW'
  END SALARY_LEVEL
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) >= 5000
ORDER BY AVG_SALARY DESC;

--18. 고객별 거래 내역
--고객 이름과 총 거래 내역(금액)을 조회하여 고객 이름을 오름차순 하세요.
SELECT C.NAME, NVL(SUM(T.AMOUNT), 0) TOTAL_AMOUNT
FROM CUSTOMERS C
LEFT OUTER JOIN ACCOUNTS A
  ON C.CUSTOMER_ID = A.CUSTOMER_ID
LEFT OUTER JOIN TRANSACTIONS T
  ON A.ACCOUNT_ID = T.ACCOUNT_ID
GROUP BY C.NAME
ORDER BY TO_NUMBER(SUBSTR(C.NAME, 10, LENGTH(C.NAME)));

--19. 부서별 직원의 평균 입사일 차이
--부서별로 평균 근속일을 계산하여 부서 이름으로 오름차순 정렬하세요. (단, 평균 근속일은 반올림하여 정수로 표현)
SELECT D.DEPARTMENT_NAME, NVL(ROUND(AVG(SYSDATE - E.HIRE_DATE)), 0) AVG_DAYS
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
  ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY TO_NUMBER(SUBSTR(D.DEPARTMENT_NAME, 12, LENGTH(D.DEPARTMENT_NAME)));

--20. 대출 금액 상위 5명 고객 조회
--대출 금액이 가장 높은 상위 5명의 고객의 이름과 대출 금액을 조회하세요. (단, 대출 금액이 동일한 경우 고객의 이름으로 오름차순)
SELECT *
FROM (
  SELECT C.NAME, SUM(L.AMOUNT) TOTAL_AMOUNT
  FROM CUSTOMERS C, LOANS L
  WHERE C.CUSTOMER_ID = L.CUSTOMER_ID
  GROUP BY C.NAME, C.CUSTOMER_ID  --동명이인이 있을 수 있으므로 CUSTOMER_ID로 GROUP BY를 사용해야 하며, NAME과 함께 사용할 수 있다.
  ORDER BY TOTAL_AMOUNT DESC, TO_NUMBER(SUBSTR(C.NAME, 10, LENGTH(C.NAME)))
)
WHERE ROWNUM <= 5;